exports.USER=require('./user')
exports.HOLIDAY=require('./holiday')
exports.DEPARTMENT=require('./department')
exports.DESIGNATION=require('./designation')
exports.BANK=require('./bank')
exports.OFFBORADINGCRITERIA= require('./Offboardingcriteria')
exports.DRS = require('./drs');
exports.AUTH = require('./auth');
exports.LEAVE = require('./leaveRequest');
exports.ORGANIZATION = require('./organization')
exports.ASSET = require('./asset')
exports.ASSETCATEGORY = require('./assetCategory')
exports.ASSETMANAGEMENT = require('./assetmanagement')