exports.USER=require('./user')
exports.HOLIDAY=require('./holiday')
exports.DEPARTMENT=require('./department')
exports.DESIGNATION=require('./designation')
exports.BANK=require('./bank')
exports.OFFBORADINGCRITERIA= require('./Offboardingcriteria')